fullnameOverride: ""

replicaCount: 1

image:
  repository: ghcr.io/tortem/homepage
  pullPolicy: IfNotPresent
  # digest: will be set by CI/CD pipeline
  tag: "latest"

imagePullSecrets: []

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: your.domain.com
  tls: 
    enabled: true
    secretName: homepage-tls
    certManager:
      clusterIssuer: letsencrypt-staging
  className: traefik

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
